# This net-attach-def defines macvlan-conf with 
#   + ips capabilities to specify ip in pod annotation and 
#   + mac capabilities to specify mac address in pod annotation
# default gateway is defined as well
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan100
spec: 
  config: '{
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "macvlan",
          "capabilities": { "ips": true },
          "master": "vlan100",
          "mode": "bridge",
          "ipam": { 
            "type": "static",
            "routes": [
              {
                "dst": "0.0.0.0/0",
                "gw": "10.100.0.254"
              },
              {
                "dst": "192.168.100.0/24",
                "gw": "10.100.0.254"
              },
              {
                "dst": "192.168.110.0/24",
                "gw": "10.100.0.254"
              }
            ] 
          }
        }, {
          "capabilities": { "mac": true },
          "type": "tuning"
        }
      ]
    }'
