apiVersion: v1
kind: Pod
metadata:
  name: be1
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
            { "name": "macvlan200",
              "ips": [ "10.200.0.253/24" ],
              "mac": "c2:b0:57:49:47:aa",
              "gateway": [ "10.200.0.1" ],
              "default-route": ["10.200.0.1" ]
            }]'
spec:
  containers:
    - name: be1
      image: "10.0.0.1:5000/myhelloapp:latest"
      ports:
        - name: http
          containerPort: 80
      env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP 
      securityContext:
        capabilities:
          add:
            - NET_ADMIN

---

apiVersion: v1
kind: Pod
metadata:
  name: be2
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
            { "name": "macvlan201",
              "ips": [ "10.200.0.253/24" ],
              "mac": "c2:b0:57:49:47:ab",
              "gateway": [ "10.200.0.2" ],
              "default-route": ["10.200.0.2" ]
            }]'
spec:
  containers:
    - name: be2
      image: "10.0.0.1:5000/myhelloapp:latest"
      ports:
        - name: http
          containerPort: 80
      env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP 
      securityContext:
        capabilities:
          add:
            - NET_ADMIN

---

apiVersion: v1
kind: Pod
metadata:
  name: be3
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
            { "name": "macvlan202",
              "ips": [ "10.200.0.253/24" ],
              "mac": "c2:b0:57:49:47:ac",
              "gateway": [ "10.200.0.3" ],
              "default-route": ["10.200.0.3" ]
            }]'
spec:
  containers:
    - name: be3
      image: "10.0.0.1:5000/myhelloapp:latest"
      ports:
        - name: http
          containerPort: 80
      env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP 
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
---

apiVersion: v1
kind: Pod
metadata:
  name: be4
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
            { "name": "macvlan203",
              "ips": [ "10.200.0.253/24" ],
              "mac": "c2:b0:57:49:47:ad",
              "gateway": [ "10.200.0.4" ],
              "default-route": ["10.200.0.4" ]
            }]'
spec:
  containers:
    - name: be4
      image: "10.0.0.1:5000/myhelloapp:latest"
      ports:
        - name: http
          containerPort: 80
      env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP 
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
---

apiVersion: v1
kind: Pod
metadata:
  name: be5
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
            { "name": "macvlan204",
              "ips": [ "10.200.0.253/24" ],
              "mac": "c2:b0:57:49:47:ae",
              "gateway": [ "10.200.0.5" ],
              "default-route": ["10.200.0.5" ]
            }]'
spec:
  containers:
    - name: be5
      image: "10.0.0.1:5000/myhelloapp:latest"
      ports:
        - name: http
          containerPort: 80
      env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP 
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
---

apiVersion: v1
kind: Pod
metadata:
  name: be6
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
            { "name": "macvlan205",
              "ips": [ "10.200.0.253/24" ],
              "mac": "c2:b0:57:49:47:af",
              "gateway": [ "10.200.0.6" ],
              "default-route": ["10.200.0.6" ]
            }]'
spec:
  containers:
    - name: be6
      image: "10.0.0.1:5000/myhelloapp:latest"
      ports:
        - name: http
          containerPort: 80
      env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP 
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
