apiVersion: v1
kind: Pod
metadata:
  name: fe1
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
            { "name": "macvlan100",
              "ips": [ "10.100.0.1/24" ],
              "mac": "c2:b0:57:49:47:f1",
              "gateway": [ "10.100.0.254" ],
              "default-route": ["10.100.0.254" ]
            },
            { "name": "macvlan200",
              "ips": [ "10.200.0.1/24" ],
              "mac": "c2:b0:57:49:47:f2"
            }
            ]'
spec:
  nodeName: node1
  hostAliases:
  - ip: "10.200.0.253"
    hostnames:
    - "hello"
  containers:
  - name: teszt
    image: 10.0.0.1:5000/myubuntu:bashed
    imagePullPolicy: Always
    ports:
    - containerPort: 80
#    lifecycle:
#      preStop:
#        exec:
#          command: ["/usr/sbin/nginx","-s","quit"]
    securityContext:
      capabilities:
        add:
          - ALL
      privileged: true

---
apiVersion: v1
kind: Pod
metadata:
  name: fe2
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
            { "name": "macvlan100",
              "ips": [ "10.100.0.2/24" ],
              "mac": "c2:b0:57:49:47:f3",
              "gateway": [ "10.100.0.254" ],
              "default-route": ["10.100.0.254" ]
            },
            { "name": "macvlan200",
              "ips": [ "10.200.0.2/24" ],
              "mac": "c2:b0:57:49:47:f4"
            }
            ]'
spec:
  nodeName: node2
  hostAliases:
  - ip: "10.200.0.253"
    hostnames:
    - "hello"
  containers:
  - name: teszt
    image: 10.0.0.1:5000/myubuntu:bashed
    imagePullPolicy: Always
    ports:
    - containerPort: 80
#    lifecycle:
#      preStop:
#        exec:
#          command: ["/usr/sbin/nginx","-s","quit"]
    securityContext:
      capabilities:
        add:
          - ALL
      privileged: true

---
apiVersion: v1
kind: Pod
metadata:
  name: fe3
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
            { "name": "macvlan100",
              "ips": [ "10.100.0.3/24" ],
              "mac": "c2:b0:57:49:47:f5",
              "gateway": [ "10.100.0.254" ],
              "default-route": ["10.100.0.254" ]
            },
            { "name": "macvlan200",
              "ips": [ "10.200.0.3/24" ],
              "mac": "c2:b0:57:49:47:f6"
            }
            ]'
spec:
  nodeName: node3
  hostAliases:
  - ip: "10.200.0.253"
    hostnames:
    - "hello"
  containers:
  - name: teszt
    image: 10.0.0.1:5000/myubuntu:bashed
    imagePullPolicy: Always
    ports:
    - containerPort: 80
#    lifecycle:
#      preStop:
#        exec:
#          command: ["/usr/sbin/nginx","-s","quit"]
    securityContext:
      capabilities:
        add:
          - ALL
      privileged: true

